import random

TRAPS = ["Magic missles shoot from a statue, object, or wall",
"Collapsing staircase creates a ramp that deposits characters into a pit at its lower end",
"A stone block falls from the ceiling",
"The room locks and the ceiling slowly lowers",
"Chute opens in floor",
"Clanging noise attracts nearby monsters",
"Touching an object triggers a disintegrate spell",
"Door or other object is coated with contact poison",
"Fire shoots out from wall, floor, or object",
"Touching an object triggers a flesh to stone spell",
"Floor collapses or is an illusion",
"Vent releases gas: blinding, acidic, obscuring, paralyzing, poisonous, or sleep-inducing",
"Floor tiles are electrified",
"Glyph of warding",
"Huge wheeled statue rolls down corridor",
"Lightning bolt shoots from wall or object",
"Locked room floods with water or acid",
"Darts shoot out of an opened chest",
"A weapon, suit of armor, or rug animates and attacks when touched (see 'Animated Objects' in the Monster Manual)",
"Pendulum, either bladed or weighted as a maul, swings across the room or hall",
"Hidden pit opens beneath characters (percent chance that a black pudding or gelatinous cube fills the bottom of the pit)",
"Hidden pit floods with acid or fire",
"Pit opens (swallowing the target) and then quickly locks shut, and then floods with water",
"Scything blade emerges from wall or object",
"Spears (possibly poisoned) spring out",
"Brittle stairs collapse over spikes",
"Thunderwave knocks characters into a pit or spikes",
"Steel or stone jaws restrain a character",
"Stone block smashes across hallway",
"Walls slide together ",
"Acidic Foam - There is a pool of acid in the room or possibly a bridge spanning a pit of acid. When triggered the trap drops a chemical into the acid causing it to erupt into foam (think mentos + soda), filling the area with acidic foam.",
"Acid Treasure - Obvious treasure in a (container, pool) of acid. Need to find a safe way to remove it.",
"Alarm - animal [chirp, howl, scream, etc], bells, gong, musical instruments, mechanical sign, signal fire, signal flare",
"Ambush - terrain designed to hide opponents / terrain that would give opponents a tactical advantage / holes that small opponents might crawl out of or drop out of / dAmbushes",
"Auto Locker - containers, doors, gate, portcullis, windows, shutters, etc",
"Auto Opener / Closer - containers, doors, gate, portcullis, shutters, sliding walls, windows, etc",
"Avalanche - rocks stacked at the top of an incline, held in place by a pin. Rocks roll down hill",
"Bee’s Nest - strategically placed bee’s nest; swarm & attack if disturbed",
"Bee's Nest Deadfall - trap causes bee's nest to fall onto or next to victim",
"Bee’s Nest Kicker - trap impacts or shakes a bee’s nest causing them to swarm & attack",
"Breakaway Flooring - floor, bridge, ledge, platform, walkway, collapsing ground",
"Breakaway Handholds - surprise those annoying thieves that climb your walls",
"Breakaway Ladder - ladder section falls away",
"Breakaway rope - There is a series of ropes or chains hanging from the ceiling spanning a pit or chasm. One could easily swing from rope to rope to cross the obstacle. Some of the ropes are damaged or deliberately designed to break away.",
"Cage - bars drops down from ceiling, bars rise up from floor",
"Caltrops - caltrops covering floor",
"Catapulting Floor - large counter weight drops, hits seesaw under floor, launches floor plate & anything standing on it into the air + spikes in impact or landing area + pit or crevasse in landing area",
"Chemical Sprayer (type) - sprays chemical in gas, liquid spray, goo, or steam form + Chemical*",
"Circular Saw Blades - extend out of slots in the floor or walls",
"Clamp Trap - bear trap, rat trap / bladed, blunt, spiked",
"Clamp Trap (chemical) - bear trap or rat trap used to break a (flask, jar) of chemical releasing (gas / liquid) + Chemical* + chemicals that ignite, explode, or produce gas when mixed + chemical that ignites on contact with air or water",
"Clamp Trap (restraint) - wrist trap, ankle trap",
"Close Line - thin wire at roughly neck height + tiny barbs + fishhooks + poison",
"Collapsing Structure - The trap destroys critical support beams causing the structure to collapse. The cave-in may be limited to a single (room / passage way / door way) or it might start a chain reaction that starts to collapse the entire dungeon.",
"Crossbow Trap - trap trigger pulls trigger on crossbow",
"Crushing Ceiling, Walls, etc",
"Deadfal Trap (animal) - bee’s nest / jar or pot filled with (ooze, scorpions, snakes, spiders, etc) / trap door releases (scorpions, snakes, spiders, etc)",
"Deadfall Trap (bludgeon) - rock, ceiling slab, heavy object / clay pot filled with chemical*",
"Deadfall Trap (liquid) - Triggering the trap causes some type of liquid to dump or spill onto victim. (acid, flammable oil, hot pepper juice, ink, insect attack pheromones, monster attractant, slime monster)",
"Deadfall Trap (piercing) - piercing weapon falls from ceiling. Ex: javelin, spear, spikes",
"Deadly Lock - The lock of a door or container is trapped. Trying to force the lock, using the wrong key, or a failed attempt to pick the lock will trigger the trap. Trap may involve a (acid sprayer, poison gas, poison needle, a trap door above or below the victim, etc)",
"Deadly Ramp - slide + blades, circular saws, grater blades, sliding weight, spikes + dump into hazard, high fall, trap, or wall of spikes",
"Deadly Stairs - changes to slide, retracts into wall, section pivots to flip upside down, + dump into hazard, high fall, or trap",
"Deadly Stair Step - blade hits ankle, slippery step, step pivots to trip victim (down stairs / over edge)",
"Door to Nowhere - door opens to the outside of a tall building, cliff, or pit + door sticks, difficult to open",
"Entombment - Upon triggering the trap, extremely large stone slabs lower blocking off all the apparent exits.",
"Fire Starter - starts fire that spreads through structure + burning causes collapse, containers of flammable material within structure, structure is flammable",
"Firing Port - arrow slit, gun port, murder hole; + closable panel; allow guards to attack intruder",
"Flood Gate - starts filling dungeon with water",
"Flood Gate - room on the other side of a door is flooded. If the door is (unlocked, opened), the water floods out",
"Flour Bomb - bags of flour drop from ceiling & bust open creating a cloud of flour. Any open flame sets off flour bomb.",
"Foot Spike - breakaway floor panel, space with upward pointing spikes + barbed spike",
"Foot Trap - breakaway floor panel, space with degree angle downward facing spikes or nails",
"Fragile Containers - if broken release - bees, acid, explosive, flammable, potions, toxic, venomous animals",
"Frozen Support - treasure Item frozen in a column of ice. the column holds up the ceiling. If attempt to break or melt the column without first finding a way to support the ceiling, the ceiling collapses.",
"Fungus - mushroom or other fungus release toxic or drug spores if disturbed",
"Gas (Drug / Toxic) - gas has a drug or toxic effect; lighter than air at top of stairs; heavier than at at bottom of stair or pit",
"Gas (Flammable) - gas may be toxic; gas explodes on contact with open flame or other ignition source",
"Gas (Non-Toxic) - displaces oxygen; heavier than air in pit, lighter than air at top of stairs",
"Grinder - moving blades, gears, parts, etc blocking a hole, door, or passageway",
"Hazardous Drink - a container or fountain that appears to be something you drink. Filled with: acid, drug, ghost pepper juice, poison, ooze monster, drink + tiny monster egg or larva, etc",
"Hot Treasure - Treasure sitting on a heat source. Causes burn damage if touched. Will cool if removed from heat source",
"Hourglass - doors close, room slowly fills with “x” substance. Acid, sand, tar, water, etc",
"Lock Pick Cutter - add difficulty to pick + if fail cuts lock pick",
"Magnifying Glass - large magnifying glass, exposed to sunlight. if victim moves into focal point, take burn damage",
"Nails - set in floor, set in climbing surfaces, embedded in rope",
"Net - drop down / on floor pulls victim up / shot like a net gun",
"Noisy Door - a door with rusty hinges or a door that scrapes against the floor when opened. Attempts to open or close the door will alert nearby people and creatures.",
"Noisy Floor - floor makes loud noise when stepped upon. creaky, tacky, covered in crunchy objects, etc. Alerts nearby people & creatures",
"Oven - doors of room close, then fire under grate in floor slowly cooks anything in room / room is full of flammable materials which are ignited by trap",
"Pendulum - axes, blades, hammers, spiked weight",
"Pit - opened / covered / covered self closing",
"Pit (options) - deep / very deep / insanely deep / drops into cage / filled with or starts filling with (acid, boiling oil, boiling water, burning oil, flammable oil, heavier than air gas, lava, liquid metal, poison, poison gas, quicksand, spikes, tar, water) / flowing river / greased walls / lava / monster in pit / nails in walls / pit wider than mouth / spell trap* / water + aquatic creatures",
"Pivot Drop - bridge, corridor, floor, stairs, walkway, etc suddenly folds down causing victim to fall",
"Poison Coating - poison or drug coating objects, containers, or door handles",
"Poisoned or Drugged Food or Drink - Food or drink that is sitting around. It has been poisoned, drugged, or has gone bad and is now toxic",
"Precariously Balanced Stack - alarm + damage from falling objects + avalanche if giant stack",
"Pull Apart - shoots barbed arrows or harpoons attached to cables from several direction, then starts retracting the cables",
"Pushing Wall - walls push victim off walkway or ledge; push victim into another trap",
"Pushing Wall of Spikes",
"Psychological (fake trap) - device looks like a trap / bodies with similar injuries along a hallway, in front of a door, or around treasure",
"Psychological (signs) - “warning Traps”, “no Traps here”, “death awaits those who can’t solve the riddle”",
"Quicksand / Mud - victim sinks in, gets stuck, possibly suffocates",
"Retracting Surface - walkway, stairs, ladder; boards, slabs, logs, handholds, etc retract into wall",
"Rolling Boulder - ice, metal, stone, etc",
"Rolling Log Bridge - cylinder or log spanning a gap, rolls when victim tries to walk on it",
"Rolling Logs - logs stacked at the top of an incline, held in place by a pin. Logs roll down hill",
"Rolling Spiked log - spiked log, ends set in ramps in the wall. If ramp ends, log builds enough speed to get launched into the air",
"Rolling Log Pit - rolling logs cover a pit. roll when someone attempts to cross dropping them into the pit. + spiked rollers, * pit traps.",
"Sabotaged Ropes - climbing, swinging, rope bridge / drop away, embedded needles + poison, greased",
"Self Destruct Lock - a lock on a container or room. If the lock if force, the wrong key is used, or on a failed lock pick attempt, the trap destroys the contents of the container or room. Note this trap is set to destroy the potential treasure not the potential thief. Destruction may involve (acid bath, being crushed, being dropped into a pit of lava, incineration, etc)",
"Slick Surface - algae, grease, oil, or ice + inclined surface, ladder, ramp, stairs, edge of pit, or edge of cliff + (broken glass, caltrops, spikes, another trap, hazardous substance, hazardous terrain, rooted monster) in fall area",
"Snare - loop of rope, grabs victim by foot & pulls – into air, into pit, over cliff, into water, into other traps, etc. +pulls foot into narrow hole",
"Spinning - axes, bar, blades, drum (bladed), drum (spiked), chains, hammers, hooks, etc",
"Stairs fold down to become a ramp or slide",
"Swing (weapon) - spring + lever arm + weapon; axe, bar, barbed spike, blade, hammer, hook, spike, spike plate, etc",
"Swinging Log - attached to ceiling by rope. Swing end first, broadside, or hanging down + spikes",
"The Hatchery - The room / chamber is full of (eggs, egg clusters, egg sacks). Touching or bumping into any of the eggs will cause a chain reaction where all the eggs start hatching. 'x' type of hungry baby creatures will swarm and attempt to consume the intruders",
"Thrower - arrows, blades, bladed disk, darts, harpoon, javelin, needles, shuriken, spears, spikes + barbed + enchantment + poison",
"Thrusting - blades, drill, harpoon, lances, needles, spears, spikes + barbed + enchantment + poison",
"Toppling Structure - a tall freestanding structure tips over and falls on the target. Ex: column, bookcase, sarcophagus, statue",
"Trap Door - ceiling + dead fall trap / floor + pit trap",
"Treasure Submerged in a hazardous substance - Item submerged in a seemingly harmless substance. The substance is actually acid, freezing (liquid nitrogen), hot, ooze monster, toxic",
"Trip Wire - wire set at ankle height, meant to trip victim + tiny barbs + fishhooks + poison + (broken glass, caltrops, spikes, another trap, hazardous substance, hazardous terrain, rooted monster) in fall area",
"Alarm -",
"Animate Dead (skeletons / zombies) - animates any corpses in the area & compels them to attack intruders",
"Animated Guardian - one or more animated weapons, animated armor, golems, statues, undead",
"Animated Relief or Wall Carvings - biting mouths, cutting shapes, grinding shapes, stabbing shapes",
"Breaking the Transformation Curse - Something (creature, cursed object) has transformed many (humanoids, monsters) into harmless creatures or statues. When the PCs figure out how to break the curse (possible to save one of their own) all of the afflicted creatures suddenly transform back to their original form. Many of these creatures may be hostile to the PCs or each other",
"Collapsing Structure - entire structure starts to collapse",
"Conceal Area - darkness, fog, illusions, mist, smoke",
"Curse - monster attraction, projectile attraction, spell attraction, unluck",
"Crippling Effect - blindness, blind rage, forget “x”, weakness",
"Damaging Effect - desiccation, disease, rapid aging",
"Death - save or die, save or die over time / disintegrate, explode, turn to dust, turn to goo, etc",
"Dispel Magic -",
"Elemental Blast - beam, cone, explosion, projectile, shotgun blast + acid, fire, frost, holy light, infernal energy, kinetic, lightning, necrotic energy, projectiles of “x”, sand blaster, sound, steam, wind, etc",
"Entangling - chains, grabbing hands, sticky floor, tentacles, vines, webs",
"Entombment - victim is pulled into surface (walls, floor, ground, etc). If fail to get free, suffocate or crushed.",
"Gateways - a series of gateways. One aimed at another. A trap (chemical sprayer, projectile, spell bolt, spell beam) is aimed at one of the gateways. When triggered it fires through one gate way to hit another and another and another…creating a (path, pattern) of danger.",
"Gravity (crushing) -",
"Gravity (random) - pull of gravity keeps changing directions + hazardous terrain",
"Gravity well - everything is pulled towards gravity well + heavy objects or sharp objects",
"Heat Metal -",
"Hypnotic Attraction - victim slowly walks towards “x” dangerous monster, terrain, or trap",
"Illusion - illusion conceals a trap / illusion makes an area look as if it is trapped / illusion makes a dangerous monster look like a much weaker or harmless creature / bait for a trap is an illusion",
"Imprisoning - frictionless bowl, levitation prison, magic barrier prison",
"Imprisoning (ice) - knee deep water; trap instant freezes water, trapping victim in ice",
"Imprisoning (object) - victim gets sucked into object. bottle, gemstone, mirror, painting, etc",
"Incapacitating Effect - euphoria, pain, paralysis, sleep",
"Invisible Damage Barrier - wall or portcullis with blades or spikes + poison",
"Invisible Wall - blocking a doorway, blocking passage, across a pit (center, far side)",
"Magical Attraction - upon touching the magically trapped bait item. All the objects in the room fly towards the victim with deadly force",
"Magic Doorway - auto closing, attempts to crush victim in door, attempts to pin victim in doorway, one way door, opens to new location each time opened, pulls victim through doorway then closes",
"Magnetic Attraction - all metal object are pulled towards trap. + pulled to ceiling, floor, trap, underwater, hazardous terrain",
"Mark - magic marks a symbol or word on the victim with a brand, scar, or tattoo. + glowing, mark reforms if damaged, mark moves to where it is visible",
"Moving Sidewalk - terrain moves underfoot; chance of knockdown, move toward trap or hazard, slam into wall.",
"Never Ending Hallway / Stairway - walk for days & never get anywhere, turn around & you haven’t gone feet. Endless one way, endless both ways.",
"One Way Door - it’s a door on one side. it’s a solid wall if your on the other side",
"Pit (bottomless) - fall forever / fall, teleport up, fall again / illusion – falling is all in victims head",
"Pit (damaging) - acid, fire, frost, holy light, infernal energy, life drain, lightning, spinning blades, etc",
"Poltergeist - all loose objects & furniture in room become projectiles",
"Potions (Bad) - deliberately sabotaged, failed experiments, out of date, overpowered",
"Potions (Mislabeled) -",
"Rage - cause victim to become enraged; victim attacks any living thing until the magic wears off",
"Raise The Dead - summons the ghost of all the corpses in the area & compels them to attack intruders",
"Separate Spirit & Body - separates victims spirit from their body. Victim effectively becomes a ghost with their body lying on the ground",
"Sinking Structure - entire dungeon sinks into the (earth, ground, ice, lava, sand, water) + keeps external environment out, lets external environment in",
"Summon - animated armor, animated statue, demon, elemental, monster, swarm",
"Teleportation to - high above ground, identical room, outside stronghold, prison cell, underwater",
"Teleport + Clones - enemies look like friends",
"Teleport + Illusion - enemies look like friends / friends look like enemies / everyone look the same",
"Teleport + Remove Gear - victim teleports, gear stays / gear teleports, victim stays / victim & gear teleport to different places",
"Teleport + Replace - victim teleports; “x” appears in victims place animal (type), monster (type), statue (material)",
"Transformation - victim transforms into: animal (type), monster (type), object, spirit form, statue (material)",
"Transformation (Terrain) - terrain within “x” radius of the trap, suddenly transforms into (acid, lava, mud, quicksand, spikes, water)",
"Trigger magic - trigger one use from all magic items within area",
"Turn Off (imprisonment) - dangerous creature, demon, golem, or spirit is trapped within barrier. Triggering trap or dispelling releases it",
"Turn Off (levitation) - platform, entire structure (castle, island, etc) is levitating. Triggering trap or dispelling it cancels the levitation causing it to fall",
"Turn Off (protection) - structure is in a hostile environment (lava, toxic gas, under sand, under water, under boiling water, vacuum, etc), magic keeps the outside environment outside. Traps turns off the protection & lets the hostile environment in or lets the air out",
"Turn Off (shielding) - hazardous energy contained within magic barrier, if barrier is dispelled or trap is triggered, the shielding turns off releasing the energy",
"Vanishing Floor - floor desolidifies, melts, turns to dust, vanishes, etc",
"Walls - bone, crystal, flesh, force, ice, iron, metal, plants, stone +bladed, +spiked, +self repairing",
"Walls (damaging) - acid, angry spirits, fire, flying (blades, debris, stones), frost, holy light, infernal energy, lava, life drain, lightning, sand storm, etc",
"Xiaolin Showdown - victim & possibly area is sucked into a pocket dimension, that takes the form of some kind of obstacle course. Victim or victims must defeat the champion of the pocket dimension at some kind of contest to escape the pocket dimension",
"",
"At the top of a set of stairs is a massive 'ogre' made of straw and hay. When the players are coming up the stairs, the enemies light the 'ogre scarecrow' on fire and push it down the stairs towards the players.",
"  The middle section of a thin stone bridge between dungeon rooms is actually made of a much weaker stone than is perceived. When a player walks across it, it begins to crumble and fall apart.",
"  Small holes in the floor hide a spear trap underneath. Kobolds have tunneled into the walls, and will stick their spears through the holes towards the players when they get close.",
"  A small vial of corrosive acid is sitting above a partially open door. When the door is pushed open, the vial falls on the one opening the door.",
"  Every odd-numbered step on a staircase is a pit trap. Two-thirds of the way down the steps, the traps start appearing on even-numbered steps.",
"  A pit trap is covered by an illusion of the floor.",
"  One of the floor tiles has a spring underneath it which will launch the victim into the ceiling when activated.",
"  A maze full of mirrors, a few of them magical which contain doppelgangers of the PCs and will proceed to hunt them.",
"  A trap that causes a bee's nest to fall onto or next to the victim.",
" Stepping on a pressure plate causes several concealed nozzles to spray acid at the victim.",
" Opening a door or chest pulls a string that pulls the trigger on crossbow. The crossbow bolt may or may not be poisoned.",
" When the trap is triggered, portcullis drop down blocking the doors. Then the walls slowly move together or the ceiling slowly lowers.",
" Deadfall Trap - When the trap is triggered, a heavy object falls onto the target area.",
" Deadly Ramp - A pressure plate on the stairs, causes the tread of the stairs to turn into a ramp. A pit opens at the bottom of the stairs.",
" Flood Gate - When triggered, doors drop down sealing the room. Grates in the ceiling or walls start filling room with water.",
" A room or section of corridor is filled with gas. Gas has a drug or toxic effect.",
" Invisible spiked portcullis bars a corridor. Victims just walk into it.",
" A net is draped across the floor and concealed by detritus. A tripwire causes a heavy counterweight to drop, lifting the net and anyone caught in it.",
" Pendulum Weapon - (axes, blades, hammers, spiked weight) swing back and forth across a corridor.",
" Open Pit Trap - a pit blocks a corridor. The pit may be filled with (acid, boiling oil, boiling water, burning oil, flammable oil, heavier than air gas, lava, liquid metal, poison, poison gas, quicksand, spikes, tar, water)",
" Pivot Bridge / Walkway - Stepping on the walkway causes it to pivot, dumping victims off the walkway.",
" A chest, placed in the center of the room, is covered with a deadly contact poison.",
" Rolling Boulder - A large boulder is place at the top on an inclined corridor. When triggered the boulder rolls down the corridor crushing anything in its path.",
" Rolling Logs - logs stacked at the top of an incline, held in place by a pin. Logs roll down hill if triggered.",
" A narrow hallway coated in grease. When the trap is set, the hallway is lit on fire.",
" Corridor filled with murky water. The good news is that the water is only about chest deep. The bad news is that there are a half dozen bear traps chained to the floor. Watch your step!",
" Ceramic jugs filled with alchemical fire, tied to thin ropes triggered to drop.",
" Tread trap that is set-up for a particular creature type and size. Comprises a small trapdoor, with angled spikes on the interior portions, that is placed over a 2-ft deep pit. The doors to the trap open easily when sufficient weight is applied but close tightly against the victims leg. The spikes, angled inward, dig into the sides of the victims leg as they attempt to pull their leg out, which also forces the door to remain closed.",
" Seesaw bridge or corridor that will dump passersby into pits or down a long fall. The party will have to be quick of foot or crafty to balance the seesaw.",
" A treasure or other object that replicates itself to fill the available space in the room. Anything trapped in the area will become crush and will eventually suffocate.",
" A thin hallway/crawlspace is blocked by a series of supports. Close inspection shows many of them to be immovable rods. Deactivation or destruction of the rods will cause the ceiling to collapse onto the entire hallway.",
" A mine cart sits at the ready with multiple levers setting its path. The wrong combination will lead to the cart flying off a cliff, crashing into a wall, sent to the den of dangerous beasts, etc.",
" A mechanism begins to spin the circular room faster and faster. At first it's just disorienting but it gradually builds until any items and creatures are firmly pressed against the wall (think saucer carnival rides). Some versions of this trap release objects like caltrops, stones, etc. When they reach high speeds to tumble pierce, and smash any within. Other versions just increase the speeds until the point where most creature will go unconcious or even die.",
" Six heroic knight statues surround a key that the players need sitting on a pedestal. A cackling flaming chandelier hangs above casting the statue's flickering shadows as long and twisted demonic shapes. A sense of dread and a perception check shows the shadows threatening/strangling/ reaching towards, etc, the player's shadows. The shadows attack when the key is disturbed.",
" Silent skeletons burst from the sarcophagi resting in the alcoves spanning both sides of the corridor. They will attempted to grapple the players and fall backwards with them back into their open sarcophagus and close the lid. The sarcophagi are filled with flesh eating insects.",
" Acidic Foam - There is a pool of acid in the room or possibly a bridge spanning a pit of acid. When triggered the trap drops a chemical into the acid causing it to erupt into foam (think mentos + soda), filling the area with acidic foam.",
" Alarm - A pressure plate or tripwire triggers a bell or gong. The sound of the alarm alerts guards. If multiple alarm traps are in the area, each one has a different sound so the guards know where the intruder is.",
" Breakaway handholds - There are small handholds in a wall spanning a pit or chasm. Some of these handholds are weak or deliberately designed to break away when enough weight is placed upon them.",
" Breakaway ladder - A section of ladder is damaged or deliberately designed to break when enough weight is placed upon it.",
" Breakaway rope - There is a series of ropes or chains hanging from the ceiling spanning a pit or chasm. One could easily swing from rope to rope to cross the obstacle. Some of the ropes are damaged or deliberately designed to break away.",
" Breaking the Transformation Curse - Something (creature, cursed object) has transformed many (humanoids, monsters) into harmless creatures or statues. When the PCs figure out how to break the curse (possible to save one of their own) all of the afflicted creatures suddenly transform back to their original form. Many of these creatures may be hostile to the PCs or each other",
" Collapsing Structure - The trap destroys critical support beams causing the structure to collapse. The cave-in may be limited to a single (room / passage way / door way) or it might start a chain reaction that starts to collapse the entire dungeon.",
" Deadfal Trap (animal) - Triggering the trap cause a dangerous animal (scorpion, slime monster, snake, spider, etc) or a swarm of dangerous animals to fall on the victim. bee’s nest / jar or pot filled with 'x' / trap door releases 'X'",
" Deadfall Trap (liquid) - Triggering the trap causes some type of liquid to dump or spill onto victim. (acid, flammable oil, hot pepper juice, ink, insect attack pheromones, monster attractant, slime monster)",
" Deadly Lock - The lock of a door or container is trapped. Trying to force the lock, using the wrong key, or a failed attempt to pick the lock will trigger the trap. Trap may involve a (acid sprayer, poison gas, poison needle, a trap door above or below the victim, etc)",
" Deadly Stair Step - One of the treads of the staircase is fake. It is actually a board supported by springs and has tiny little holes in it. Underneath the step is a set of nail positioned so that when the board comes down the nails will come up through the holes. The nails may have tiny barbs, they may be poisoned, or they might just be rusty. Additionally, the stair suddenly giving way underfoot may cause the victim to fall down the stairs.",
" Door to Nowhere - Door opens to the outside of a tall building, a cliff, or a pit. The door appears to be jammed and may require a Str check to open. Anyone who uses force to open the door has to make a Dex check to keep from falling.",
" Entombment - Upon triggering the trap, extremely large stone slabs lower blocking off all the apparent exits.",
" Firing Port - An arrow slit, gun port, murder hole that allows guards to attack intruders while remaining mostly safe from return fire. The firing port may have a closable panel affording the guards greater protection if needed.",
" Flamethrower - Several statues line the trapped area. When triggered the statues breath fire on the target area. For additional fun, the statues breath sticky flaming gel that burns for several turns.",
" Fungus - mushroom or other fungus release toxic or drug spores if disturbed",
" Gas (Non-Toxic) - A gas pocket displaces oxygen in the area. Creatures will begin to suffocate and may not even realize they are suffocating. Signs of trouble: flames in the area are suddenly extinguished and voices of creatures get really high or really low. Heavier than air gas in pit or at the bottom of stairs or incline / lighter than air gas at top of stairs or at the top of an incline.",
" Hypnotic Attraction - A magic sigil or item cause the victim to slowly walk towards “x” (dangerous monster, dangerous terrain, or trap)",
" Magical Attraction - upon touching the magically trapped bait item, all the objects in the room fly towards the victim with deadly force",
" Magical One Way Door - it’s a door on one side. it’s a solid wall if your on the other side",
" Magical Rage - upon touching the magically trapped bait item, all creatures within 'X' radius are afflicted with a mindless rage and begin attacking any and all living creatures.",
" Magical Raising the Dead - upon triggering the trap, it animates all the corpses within 'X' range. All the newly created undead are hostile to the intruders. Alternatively the trap may raise up angry ghost from all the corpses.",
" Magical Teleportation Trap - upon triggering the trap the victim is teleported (high in the air, into a cage, into a monster pit, into another trap, to another part of the dungeon,).",
" Magical Transformation (creature) - upon touching the magically trapped bait item, the victim is transformed into 'X' type of (creature, monster). For additional fun, the victim has the mind of a monster and attacks their companions / the victim has the mind of a terrified prey animal and runs away from their companions.",
" Magical Transformation (statue) - upon touching the magically trapped bait item, the victim starts slowly transforming into a statue of 'X' material (bone, ceramic, chitin, clay, crystal, glass, ice, metal, salt, stone, wood, etc). There may be a cure somewhere in the dungeon that can be used before they completly transform.",
" Methane Gas Pocket - a pocket of methane gas has collected in the area. The gas is slightly toxic and will explode if ignited by any open flames or other ignition source.",
" Mislabeled Potions - Some being or creature has stored potions here. At least some of the potions in question have been mislabeled so they will have a random effect instead of the intended effect.",
" Nails - Nails set at strategic points. Set in floor, set in climbing surfaces, embedded in ropes for climbing or swinging.",
" Noisy Door - a door with rusty hinges or a door that scrapes against the floor when opened. Attempts to open or close the door will alert nearby people and creatures.",
" Noisy Floor - Floor makes loud noise when stepped upon. The floor may be creaky, squeaky, tacky, or covered in crunchy objects. Noise from the floor alerts nearby people & creatures.",
" Pull Apart - Upon triggering the trap shoots barbed arrows or harpoons attached to cables from several direction, then counterweights drop causing all the cables to start retracting.",
" Pushing Wall - Trap is placed next to a narrow walkway or ledge. When triggered the walls push victim off walkway or ledge.",
" Quicksand / Mud - victim sinks in, gets stuck, possibly suffocates",
" Retracting Surface - Trap is part of a walkway, stairs, a ladder, handholds. When the trap is triggered the 'walk way' retracts into the wall causing the victim to fall.",
" Self Destruct Lock - a lock on a container or room. If the lock if force, the wrong key is used, or on a failed lock pick attempt, the trap destroys the contents of the container or room. Note this trap is set to destroy the potential treasure not the potential thief. Destruction may involve (acid bath, being crushed, being dropped into a pit of lava, incineration, etc)",
" Slick Surface - algae, grease, oil, or ice coats an inclined surface, a ladder, an inclined surface, a ramp, stairs, the edge of a pit, the edge of cliff, the edge of a river, etc. Sliding down the surface may cause the victim to fall into another trap or it may bring the victim within range of a monster that is (chained, rooted) in place.",
" Snare - A loop of rope attached to a heavy counterweight. When triggered the rope grabs victim by foot & pulls. The counterweight may be set so that it pulls the victim (into air, into a pit, over cliff, into water, into other traps, etc).",
" Swinging Ram - A heavy log attached to the ceiling by ropes. When the trap is triggered it swings down smashing into the target area. For additional fun of these traps can be placed facing each other so that they smash the victim between them.",
" The Hatchery - The room / chamber is full of (eggs, egg clusters, egg sacks). Touching or bumping into any of the eggs will cause a chain reaction where all the eggs start hatching. 'X' type of hungry baby creatures will swarm and attempt to consume the intruders",
" Turn Off (imprisonment) - a dangerous (creature, demon, entity, golem, or spirit) is trapped within barrier. Triggering the trap turn off the barrier. Alternatively, the bait 'magic item' might be what is powering the barrier.",
" Weapon Thrower - Upon triggering the trap it shoots or throws (arrows, blades, bladed disk, darts, harpoon, javelin, needles, shuriken, spears, or spikes) at the target area. For additional fun, the weapons may be barbed, poisoned, or rusty.",
" Weapon Thruster - Upon triggering the trap a thrusting weapon (blades, harpoon, lances, needles, spears, spikes) extends out of holes in a nearby (ceiling, floor, wall) or other surface. The holes may be concealed with a thin layer of easily breakable material like paper-mache or a thin layer of plaster. For additional fun, the weapons may be barbed, poisoned, or rusty.",
" A statue of a dwarf with a Glyph of Warding on its chest that, when triggered, casts Burning Hands with damage appropriate for a 3rd-level spell slot, originating from the statue's hands.",
" The Sleeping Beast - there is a powerful creature or a large pack of creatures sleeping in the area. The slightest noise might wake them.",
" Dungeon has a (gateway, portal) to it that will only remain open for 'X' amount of time. If the PCs don't complete their mission within the time limit they will be trapped where ever the dungeon is located. Alternatively the entire dungeon might only appear on the prime material plane for 'X' amount of time, after that it vanishes back to another dimension.",
" Dungeon is about to be destroyed. A (earthquake, magical disaster, meteor, tidal wave, volcano, etc) is about to hit the dungeon. PCs must get whatever they need from the dungeon and escape before the time runs out.",
" Dungeon is about to be overrun by enemies (dungeon denizen's reinforcements / 3rd party hostile forces). PCs must get whatever they need from the dungeon and escape before it's too late.",
" A dungeon with a dampness problem has several puddles in the floor. At least two or three of these unavoidable puddles are actually deep holes, filled with water. The water is filled with crustaceans. Treat as aquatic centipedes.",
" A hidden sliding stone wall splits the party by closing a hallway ten feet behind the member on point. Two fiendish animals are summoned to attack or chase the lead character now that they are separated. The wall and summoning trap resets after two hours.",
" An enchanted pool of water that gives anyone that touches it shadowy visions of thier own death. Creatures that recieve these visions take psychic damage.",
" A pool of filthy water that is infected with a disease.",
" The shadows in this area are hungry. Any creature that ends its turn in darkness takes force damage.",
" A poisonous river of quicksilver.",
" A pressure plate that triggers a catapult that launches you outside of the dungeon (or back to a previous room of the dungeon).",
" The Support trap - When activated creates a ticking noise that follows the party around the room. Making any further trap checks with disadvantage.",
" The Heads Up Trap (for when you're feeling generous) - The click of the pressure plate is just loud enough for you to hear, but it's quickly drowned out by the pounding of your heart as you realize the mistake you've made. You hear a powerful whoosh of air at your head height and... nothing. You look cautiously over and see a hole in the wall, small, but deep. As you look around, there at your feet are a few crushed/spent darts with feathers. Seems like you should pay closer attention...",
" An enchanted piece of the environment (door, window, bridge, floor panel) that has a powerful version of the enlarge/reduce spell on it. A creature coming in contact with the enchanted item with bare skin makes a save or shrinks down to 1/100th their size. Once leaving the item, they revert after minute. Any item coming in contact with the enchanted environment piece fails automatically. This would pull boots and gloves off adventurers as they shrink down rapidly off their bodies.",
" Long stairwell is rigged to fall flat (turning stairs into a ramp) once a pressure plate is triggered. This also releases a grease spell on the stairs, aiding to the slickness. At the bottom of the stairs pops open a small compartment with spikes ready to stop your descent rather pointedly.",
" A bronzed octopus shaped chandelier fixed atop the ceiling. When players walk underneath it, it squirts an acidic blank ink on them.",
" A room filled with sentient explosive candles with little legs. When players enter the room without any light source the candles fuses light up and run towards the players, exploding when they get close.",
"A flower in a small clay pot is upon a raised platform in the center of the room. If players disturb the flower in any way vines start sprouting out of the cracks in the walls and through the holes in floor. They crawl towards the players to avenge their flower friend.",
"A room that builds up electricity the more the people in it move.",
"There is a very large and obvious pressure plate in the middle of a long hallway, connected to a dart trap at the end. If the players step on any files besides the apparent pressure plate at that spot in the hallway, the trap will be triggered.",
"A magical light spins across the walls, making anyone who stays in the room too long dizzy.",
"Sinkers and Floaters - A pool with alligators (or whatever aquatic death creatures you desire) in it blocks the path to the other side. There are a series of stones across it, some of the stones are sturdy and real, some of them are actually made of light driftwood painted to look like the other rocks. They are also roped to the bottom of the pool so they look like sturdy rocks. If a PC steps on one of the fake rocks, it will sink quickly under their feet. If a PC is being too slow crossing the pool, the creatures will attack the PC while they are on the rocks.",
"Confusion-inducing floor tiles and unholy skulls triggered by a bound prisoner.",
"Acidic spears and fatiguing crossbows triggered by delicate magic-detecting spheres.",
"Blinding ballistae and fungus-encrusted bolas triggered by a jeweled pillar.",
"Shadowy monster summoners and ethereal bear traps triggered by a sacrificial bowl and dagger.",
"Sleep-inducing darts and entangling spiked pits triggered by floor plates.",
"Radiant barbed nets and moldy animated statues triggered by a weapon on an altar.",
"Forceful caltrops and icy metal disks triggered by giant knockers.",
"Gravity reversing razor-wire and flaming swinging blades triggered by steep stairs.",
"Gaseous crushing walls and fear-inducing swinging glaives triggered by iron-bound chests.",
"Silencing swinging spiked chains and dazzling beams triggered by beams of light.",
"Stunning cages and poisonous rocks triggered by hidden magnets.",
"Diseased snares and nauseating glyphs triggered by an onyx demonic skull.",
"Explosive scythes and deafening hammers triggered by a gilded sarcophagus.",
"Arcane catapults and energy-draining javelins triggered by a hidden enemy.",
"Ooze-covered spores and necrotic pillars triggered by tiny threads strung across the room.",
"Invisible swinging axes and sonic alarms triggered by the correct answer to an easy riddle.",
"Psychic swinging glaives and negative energy alarms triggered by a jeweled skull.",
"Panic-inducing bolas and electrical skulls triggered by alternating floor tiles.",
"Infested animated statues and nauseating catapults triggered by a rough gemstone.",
"Negative energy bear traps and silencing javelins triggered by golden angelic statue.",
"Invisible crossbows and stunning floor tiles triggered by a crystal goblet on a pedestal.",
"Unholy swinging spiked chains and energy-draining barbed nets triggered by an idol on pedestal.",
"Sleep-inducing spores and forceful cages triggered by hanging ropes.",
"Shadowy hammers and gravity reversing snares triggered by a jeweled crown on a skeleton's head.",
"Sonic razor-wire and fungus-encrusted caltrops triggered by mischievous ghosts.",
"Diseased darts and radiant ballistae triggered by an old wooden chest.",
"Dazzling scythes and necrotic crushing walls triggered by an ornate throne.",
"Panic-inducing spears and icy pillars triggered by a child's toy.",
"Ooze-covered spiked pits and entangling glyphs triggered by a forbidden scroll.",
"Electrical monster summoners and moldy swinging axes triggered by tripwires.",
"Confusion-inducing beams and fatiguing rocks triggered by an ancient leatherbound tome.",
"Blinding swinging blades and acidic metal disks triggered by delicate pots.",
"Explosive javelins and flaming razor-wire triggered by glass orbs that vibrate with sound.",
"Fear-inducing spores and deafening scythes triggered by iron-bound chests.",
"Gaseous swinging glaives and poisonous spears triggered by a forbidden scroll.",
"Ethereal pillars and arcane monster summoners triggered by a weapon on an altar.",
"Psychic barbed nets and infested floor tiles triggered by an ornate throne.",
"Nauseating alarms and arcane spiked pits triggered by a jeweled crown on a skeleton's head.",
"Panic-inducing rocks and negative energy swinging blades triggered by a sacrificial bowl and dagger.",
"Blinding beams and shadowy hammers triggered by an idol on pedestal.",
"Fatiguing catapults and stunning swinging axes triggered by a rough gemstone.",
"Necrotic metal disks and forceful glyphs triggered by an ancient leatherbound tome.",
"Dazzling crossbows and ooze-covered crushing walls triggered by an onyx demonic skull.",
"Flaming skulls and poisonous snares triggered by a gilded sarcophagus.",
"Electrical cages and explosive swinging spiked chains triggered by a jeweled pillar.",
"Gravity reversing animated statues and silencing bolas triggered by floor plates.",
"Infested ballistae and psychic darts triggered by a crystal goblet on a pedestal.",
"Diseased bear traps and energy-draining caltrops triggered by beams of light.",
"Gaseous darts and deafening crossbows triggered by alternating floor tiles.",
"Confusion-inducing barbed nets and fungus-encrusted skulls triggered by a bound prisoner.",
"Sonic beams and invisible pillars triggered by delicate pots.",
"Radiant floor tiles and ethereal hammers triggered by hidden magnets.",
"Moldy swinging glaives and unholy alarms triggered by a jeweled skull.",
"Fear-inducing monster summoners and acidic metal disks triggered by delicate magic-detecting spheres.",
"Entangling spears and sleep-inducing ballistae triggered by mischievous ghosts.",
"Invisible scythes and sleep-inducing glyphs triggered by a hidden enemy.",
"Negative energy caltrops and radiant snares triggered by golden angelic statue.",
"Explosive animated statues and fear-inducing swinging axes triggered by glass orbs that vibrate with sound.",
"Blinding catapults and stunning rocks triggered by tripwires.",
"Fungus-encrusted spiked pits and acidic cages triggered by steep stairs.",
"Shadowy spores and forceful swinging spiked chains triggered by the correct answer to an easy riddle.",
"Electrical bear traps and moldy bolas triggered by tiny threads strung across the room.",
"Entangling swinging blades and ethereal javelins triggered by a child's toy.",
"Deafening crushing walls and flaming razor-wire triggered by giant knockers.",
"Panic-inducing animated statues and silencing javelins triggered by an old wooden chest.",
"Gaseous rocks and poisonous hammers triggered by hanging ropes.",
"Diseased swinging blades and gravity reversing darts triggered by the correct answer to an easy riddle.",
"Dazzling razor-wire and nauseating scythes triggered by an ancient leatherbound tome.",
"Unholy crossbows and arcane caltrops triggered by delicate pots.",
"Icy bolas and psychic pillars triggered by iron-bound chests.",
"Infested glyphs and confusion-inducing swinging spiked chains triggered by delicate magic-detecting spheres.",
"Fatiguing barbed nets and sonic spores triggered by a forbidden scroll.",
"Necrotic floor tiles and energy-draining crushing walls triggered by hidden magnets.",
"Ooze-covered metal disks and invisible cages triggered by a weapon on an altar.",
"Energy-draining snares and stunning catapults triggered by steep stairs.",
"Forceful bear traps and flaming spiked pits triggered by a child's toy.",
"Gaseous ballistae and blinding swinging glaives triggered by beams of light.",
"Moldy alarms and negative energy spears triggered by a crystal goblet on a pedestal.",
"Shadowy monster summoners and icy swinging axes triggered by an old wooden chest.",
"Gravity reversing beams and electrical skulls triggered by a sacrificial bowl and dagger.",
"Entangling floor tiles and diseased monster summoners triggered by an onyx demonic skull.",
"Silencing bear traps and invisible animated statues triggered by tripwires.",
"Acidic swinging glaives and sonic razor-wire triggered by alternating floor tiles.",
"Dazzling glyphs and necrotic rocks triggered by a jeweled crown on a skeleton's head.",
"Ooze-covered javelins and ethereal beams triggered by tiny threads strung across the room.",
"Panic-inducing skulls and confusion-inducing barbed nets triggered by a jeweled pillar.",
"Infested crushing walls and radiant catapults triggered by an idol on pedestal.",
"Nauseating swinging spiked chains and fungus-encrusted scythes triggered by golden angelic statue.",
"Explosive swinging blades and unholy pillars triggered by glass orbs that vibrate with sound.",
"Poisonous swinging axes and arcane darts triggered by a hidden enemy.",
"Fear-inducing alarms and deafening ballistae triggered by an ornate throne.",
"Psychic bolas and fatiguing caltrops triggered by a jeweled skull.",
"Explosive metal disks and dazzling spiked pits triggered by a gilded sarcophagus.",
"Fatiguing snares and electrical spears triggered by giant knockers.",
"Panic-inducing crossbows and energy-draining cages triggered by hanging ropes.",
"Silencing spores and confusion-inducing hammers triggered by a bound prisoner.",
"Ooze-covered alarms and gaseous hammers triggered by a rough gemstone.",
"Arcane beams and invisible barbed nets triggered by floor plates.",
"Icy floor tiles and forceful spiked pits triggered by mischievous ghosts.",
"Diseased spears and psychic swinging spiked chains triggered by an onyx demonic skull.",
"Pit trap",
"Spike trap",
"Poison dart trap",
"Arrow trap",
"Net trap",
"Blade trap",
"Ceiling crush trap",
"Fire trap",
"Acid spray trap",
"Electric shock trap",
"Gas trap",
"Collapsing floor trap",
"Wall scythe trap",
"Water-filled room trap",
"Paralyzing trap",
"Summoning trap",
"Illusion trap",
"Teleportation trap",
"Reverse gravity trap",
"Door trap (e.g. trapped door, portcullis, etc.)",
"Pressure plate trap",
"Staircase trap",
"False floor trap",
"Bear trap",
"Choking gas trap",
"Explosive trap",
"Freezing trap",
"Glue trap",
"Guillotine trap",
"Holy/Unholy trap",
"Lava trap",
"Magic spell trap",
"Noisemaking trap",
"Rotating room trap",
"Shocking grasp trap",
"Smoke trap",
"Stinking cloud trap",
"Tanglefoot bag trap",
"Venomous snake trap",
"Whirlwind trap",
"    Alarm trap",
"Cage trap",
"Camouflaged trap",
"Ceiling net trap",
"Chute trap",
"Collapsing ceiling trap",
"Confusion gas trap",
"Decapitation trap",
"Disintegration trap",
"Entanglement trap",
"Flooding trap",
"Illusionary wall trap",
"Magic mouth trap",
"Mimic trap",
"Paralyzation field trap",
"Poison needle trap",
"Rolling boulder trap",
"Rust trap",
"Shrinking room trap",
"Telekinesis trap",
"    Anti-magic field trap",
"Black pudding trap",
"Chain trap",
"Crystal shard trap",
"Dimension door trap",
"Ejection trap",
"Enervation trap",
"Flashbang trap",
"Ghost sound trap",
"Invisibility trap",
"Leaping trap",
"Magic aura trap",
"Necrotic trap",
"Oozing trap",
"Portal trap",
"Psychic trap",
"Reflecting trap",
"Sonic trap",
"Time trap",
"Web trap",
"    Anti-teleportation trap",
"Blinding trap",
"Chain lightning trap",
"Control weather trap",
"Death magic trap",
"Earth Tremor trap",
"Fear trap",
"Force cage trap",
"Glitterdust trap",
"Harm trap",
"Insect plague trap",
"Light trap",
"Magic drain trap",
"Necrotic energy trap",
"Plant growth trap",
"Quicksand trap",
"Reverse gravity trap",
"Sleep trap",
"Telepathic trap",
"Wall of force trap",
"Anti-invisibility trap",
"Ballista trap",
"Contagion trap",
"Delayed blast fireball trap",
"Earthen grasp trap",
"Fear aura trap",
"Fireball trap",
"Geas trap",
"Hypnotic pattern trap",
"Ice storm trap",
"Lightning bolt trap",
"Magic jar trap",
"Necrotic burst trap",
"Petrifying trap",
"Raise dead trap",
"Scorching ray trap",
"Thorn whip trap",
"Unseen servant trap",
"Vampiric touch trap",
"Wall of thorns trap"]


def main():
    for i in range(10):
        print(f"{i}: {random.choice(TRAPS)}")

main()